# ---
# apiVersion: rbac.authorization.k8s.io/v1beta1
# kind: Role
# metadata:
#   name: fabric8-admin
#   namespace: devops-platform
# rules:
# # Just an example, feel free to change it
# - apiGroups: [""]
#   resources: ["pods"]
#   verbs: ["get", "watch", "list"]
#
# ---
# apiVersion: rbac.authorization.k8s.io/v1beta1
# kind: RoleBinding
# metadata:
#   name: fabric8-rbac
#   namespace: devops-platform
# subjects:
#   - kind: ServiceAccount
#     name: default
# roleRef:
#   kind: Role
#   name: fabric8-admin
#   apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Namespace
metadata:
  name: utility

---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: utility
 namespace: utility

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: utility-rbac
subjects:
  - kind: ServiceAccount
    name: utility
    namespace: utility
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
