apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: ReplicaSet
metadata:
  name: infra-helper
  namespace: utility
  labels:
    app: infrastructure
    tier: utility
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  selector:
    matchLabels:
      tier: utility
    matchExpressions:
      - {key: tier, operator: In, values: [utility]}
  template:
    metadata:
      labels:
        app: infrastructure
        tier: utility
    spec:
      serviceAccount: utility
      serviceAccountName: utility
      containers:
      - name: php-redis
        image: gopinatht/infra-helper
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        
